package com.olehkobylianskyi.familypoints.entity;

public enum TaskAuditEventType {
    DEFINITION_CREATED,
    DEFINITION_UPDATED,
    DEFINITION_ACTIVATED,
    DEFINITION_DEACTIVATED,

    INSTANCE_CREATED,
    INSTANCE_GENERATED,
    INSTANCE_CLAIMED,
    INSTANCE_STARTED,
    INSTANCE_PAUSED,
    INSTANCE_RESUMED,
    INSTANCE_CANCELLED,
    INSTANCE_RELEASED,
    INSTANCE_COMPLETED,
    INSTANCE_MISSED,
    INSTANCE_EXCUSED,
    INSTANCE_DELEGATED
}
