package com.olehkobylianskyi.familypoints.service;
import com.olehkobylianskyi.familypoints.dto.*; import com.olehkobylianskyi.familypoints.entity.*; import com.olehkobylianskyi.familypoints.exception.ResourceNotFoundException; import com.olehkobylianskyi.familypoints.repository.*;
import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service public class MemberGroupService {
 private final WorkspaceRepository families; private final WorkspaceMemberRepository members; private final MemberGroupRepository groups; private final GroupRoleRepository roles; private final GroupMembershipRepository memberships; private final GroupCompositionRepository compositions; private final PointTypeRepository pointTypes; private final GroupPointTransactionRepository groupLedger; private final GroupPermissionGrantRepository permissionGrants; private final RoleSetRepository roleSets; private final LegacyGroupRoleBridgeService roleBridge;
 public MemberGroupService(WorkspaceRepository a,WorkspaceMemberRepository b,MemberGroupRepository c,GroupRoleRepository d,GroupMembershipRepository e,GroupCompositionRepository f,PointTypeRepository p,GroupPointTransactionRepository l,GroupPermissionGrantRepository pg,RoleSetRepository rs,LegacyGroupRoleBridgeService rb){families=a;members=b;groups=c;roles=d;memberships=e;compositions=f;pointTypes=p;groupLedger=l;permissionGrants=pg;roleSets=rs;roleBridge=rb;}
 @Transactional public MemberGroupResponse createGroup(Long workspaceId,String name,String description){Workspace f=workspace(workspaceId);return response(groups.save(new MemberGroup(f,name.trim(),blank(description))));}
 @Transactional(readOnly=true) public List<MemberGroupResponse> getGroups(Long workspaceId){workspace(workspaceId);return groups.findByWorkspaceIdAndActiveTrueOrderByNameAsc(workspaceId).stream().map(this::response).toList();}
 @Transactional public MemberGroupResponse updateGroup(Long workspaceId,Long groupId,String name,String description,boolean showInNavigation){MemberGroup g=group(workspaceId,groupId);g.setName(name.trim());g.setDescription(blank(description));g.setShowInNavigation(showInNavigation);return response(groups.save(g));}
 @Transactional public void deactivateGroup(Long workspaceId,Long groupId){MemberGroup g=group(workspaceId,groupId);g.setActive(false);groups.save(g);}
 @Transactional public MemberGroupResponse addRole(Long workspaceId,Long groupId,String name,String description,Long roleSetId){MemberGroup g=group(workspaceId,groupId);if(roles.existsByMemberGroupIdAndNameIgnoreCase(groupId,name.trim()))throw new IllegalArgumentException("Group role already exists: "+name);GroupRole r=new GroupRole(g,name.trim(),blank(description));if(roleSetId!=null)r.setRoleSet(roleSets.findByIdAndWorkspaceId(roleSetId,workspaceId).orElseThrow(()->new ResourceNotFoundException("Role set not found: "+roleSetId)));roles.save(r);roleBridge.syncRole(r);return response(g);}
 @Transactional public MemberGroupResponse updateRole(Long workspaceId,Long groupId,Long roleId,String name,String description,Long roleSetId){MemberGroup g=group(workspaceId,groupId);GroupRole r=roles.findByIdAndMemberGroupId(roleId,groupId).orElseThrow(()->new ResourceNotFoundException("Group role not found: "+roleId));r.setName(name.trim());r.setDescription(blank(description));r.setRoleSet(roleSetId==null?null:roleSets.findByIdAndWorkspaceId(roleSetId,workspaceId).orElseThrow(()->new ResourceNotFoundException("Role set not found: "+roleSetId)));roles.save(r);roleBridge.syncRole(r);return response(g);}
 @Transactional public MemberGroupResponse updateMemberRoles(Long workspaceId,Long groupId,Long memberId,Set<Long> roleIds){return addMember(workspaceId,groupId,memberId,roleIds);}
 @Transactional public MemberGroupResponse addMember(Long workspaceId,Long groupId,Long memberId,Set<Long> roleIds){MemberGroup g=group(workspaceId,groupId);WorkspaceMember m=members.findByIdAndWorkspaceId(memberId,workspaceId).orElseThrow(()->new ResourceNotFoundException("Workspace member not found: "+memberId));GroupMembership x=memberships.findByMemberGroupIdAndMemberId(groupId,memberId).orElseGet(()->new GroupMembership(g,m));x.setActive(true);x.getRoles().clear();for(Long id:roleIds==null?Set.<Long>of():roleIds)x.addRole(roles.findByIdAndMemberGroupId(id,groupId).orElseThrow(()->new ResourceNotFoundException("Group role not found: "+id)));memberships.save(x);roleBridge.syncMembership(x);return response(g);}
 @Transactional public MemberGroupResponse removeMember(Long workspaceId,Long groupId,Long memberId){MemberGroup g=group(workspaceId,groupId);GroupMembership x=memberships.findByMemberGroupIdAndMemberId(groupId,memberId).orElseThrow(()->new ResourceNotFoundException("Membership not found"));x.setActive(false);memberships.save(x);roleBridge.syncMembership(x);return response(g);}
 @Transactional public MemberGroupResponse addChildGroup(Long workspaceId,Long parentId,Long childId){if(parentId.equals(childId))throw new IllegalArgumentException("A group cannot contain itself");MemberGroup p=group(workspaceId,parentId),c=group(workspaceId,childId);if(reaches(childId,parentId,new HashSet<>()))throw new IllegalArgumentException("Group cycle is not allowed");GroupComposition x=compositions.findByParentGroupIdAndChildGroupId(parentId,childId).orElseGet(()->new GroupComposition(p,c));x.setActive(true);compositions.save(x);return response(p);}
 @Transactional public MemberGroupResponse removeChildGroup(Long workspaceId,Long parentId,Long childId){MemberGroup p=group(workspaceId,parentId);GroupComposition x=compositions.findByParentGroupIdAndChildGroupId(parentId,childId).orElseThrow(()->new ResourceNotFoundException("Group composition not found"));x.setActive(false);compositions.save(x);return response(p);}
 @Transactional(readOnly=true) public Map<String,Object> resolveActors(Long workspaceId,Long groupId){group(workspaceId,groupId);LinkedHashSet<Long> gs=new LinkedHashSet<>(),ms=new LinkedHashSet<>();collect(groupId,gs,ms,new HashSet<>());return Map.of("rootGroupId",groupId,"groupIds",gs,"memberIds",ms);}
 @Transactional(readOnly=true) public List<GroupPermissionGrantResponse> getPermissionGrants(Long workspaceId,Long groupId){group(workspaceId,groupId);return permissionGrants.findByMemberGroupIdOrderByIdAsc(groupId).stream().map(GroupPermissionGrantResponse::from).toList();}
 @Transactional public GroupPermissionGrantResponse addPermissionGrant(Long workspaceId,Long groupId,Long roleId,GroupPermission permission,GroupPermissionScope scope){MemberGroup g=group(workspaceId,groupId);GroupRole r=roles.findByIdAndMemberGroupId(roleId,groupId).orElseThrow(()->new ResourceNotFoundException("Group role not found: "+roleId));boolean exists=permissionGrants.findByGroupRoleIdAndPermission(roleId,permission).stream().anyMatch(x->x.getScope()==scope);if(exists)throw new IllegalArgumentException("Permission grant already exists");return GroupPermissionGrantResponse.from(permissionGrants.save(new GroupPermissionGrant(g,r,permission,scope)));}
 @Transactional public void removePermissionGrant(Long workspaceId,Long groupId,Long grantId){group(workspaceId,groupId);GroupPermissionGrant grant=permissionGrants.findByIdAndMemberGroupId(grantId,groupId).orElseThrow(()->new ResourceNotFoundException("Permission grant not found: "+grantId));permissionGrants.delete(grant);}
 @Transactional public MemberGroupResponse addPoints(Long workspaceId,Long groupId,Long pointTypeId,int amount,PointTransactionType type,String description){MemberGroup g=group(workspaceId,groupId);PointType p=pointTypes.findByIdAndWorkspaceId(pointTypeId,workspaceId).orElseThrow(()->new ResourceNotFoundException("Point type not found: "+pointTypeId));if(amount==0)throw new IllegalArgumentException("Amount cannot be zero");int signed=Math.abs(amount);if(type==PointTransactionType.SPEND||type==PointTransactionType.PENALTY)signed=-signed;else if(type==PointTransactionType.ADJUSTMENT)signed=amount;groupLedger.save(new GroupPointTransaction(g,p,signed,type,blank(description)));return response(g);}
 private void collect(Long id,Set<Long> gs,Set<Long> ms,Set<Long> seen){if(!seen.add(id))return;for(GroupMembership m:memberships.findByMemberGroupIdAndActiveTrueOrderByIdAsc(id))ms.add(m.getMember().getId());for(GroupComposition c:compositions.findByParentGroupIdAndActiveTrueOrderByIdAsc(id)){Long child=c.getChildGroup().getId();gs.add(child);collect(child,gs,ms,seen);}}
 private boolean reaches(Long from,Long target,Set<Long> seen){if(from.equals(target))return true;if(!seen.add(from))return false;for(GroupComposition c:compositions.findByParentGroupIdAndActiveTrueOrderByIdAsc(from))if(reaches(c.getChildGroup().getId(),target,seen))return true;return false;}
 private MemberGroupResponse response(MemberGroup g){List<MemberGroupResponse.Balance> bs=pointTypes.findByWorkspaceIdAndActiveTrueOrderBySortOrderAsc(g.getWorkspace().getId()).stream().map(p->new MemberGroupResponse.Balance(p.getId(),p.getCode(),p.getName(),groupLedger.getBalance(g.getId(),p.getId()))).toList();return MemberGroupResponse.from(g,roles.findByMemberGroupIdOrderByNameAsc(g.getId()),memberships.findByMemberGroupIdAndActiveTrueOrderByIdAsc(g.getId()),compositions.findByParentGroupIdAndActiveTrueOrderByIdAsc(g.getId()),compositions.findByChildGroupIdAndActiveTrueOrderByIdAsc(g.getId()),bs);}
 private MemberGroup group(Long f,Long id){return groups.findByIdAndWorkspaceId(id,f).orElseThrow(()->new ResourceNotFoundException("Member group not found: "+id));} private Workspace workspace(Long id){return families.findById(id).orElseThrow(()->new ResourceNotFoundException("Workspace not found: "+id));} private String blank(String s){return s==null||s.isBlank()?null:s.trim();}
}
